version: '2'
services:
    logposterendpoint-elasticsearch:
        container_name: logposterendpoint-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/LogPosterEndpoint/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
